---

- name: Initial guards
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Check for known problematic operating systems
    fail:
      msg: "{{ os }} is known to be unable to build a tinyipa image. Exiting..."
    when: os == "centos7.0"

- import_playbook: build-vm.yml
- import_playbook: prepare-devstack.yml
- import_playbook: build-ipa-image.yml
