---
- name: Find out the VM ip address
  hosts: localhost
  vars:
    found_ip: false
  tasks:

  - name: See if we need to go find the VM IP address
    set_fact:
      found_ip: true
    when: groups["vms"] is defined and (groups["vms"]|length>0)

  - name: grab a routed IP address for the vm
    become: yes
    shell: |
        virsh domifaddr "{{ name }}" |
        tail -n +3 | awk '{print $4}' |
        cut -d'/' -f1 |
        while read ipa ; do
            ping -c1 $ipa >& /dev/null;
            [[ $? -eq 0 ]] && echo "$ipa" && break;
        done
    register: ip_addr
    delegate_to: localhost
    until: ip_addr.rc == 0
    delay: 10
    retries: 12
    when: found_ip == false

  - name: ensure we found an IP address for this vm
    fail: msg="Could not find IP Address for '{{ name }}'"
    when: (ip_addr.stdout is not defined or ip_addr.stdout == "") and found_ip == false

  - name: avoid the ssh host authentication query
    shell: |
      ssh -O exit "{{ ip_addr.stdout }}"
      ssh-keygen -R "{{ ip_addr.stdout }}"
      ssh -o StrictHostKeyChecking=no -v root@"{{ ip_addr.stdout }}" true
    register: ssh_result
    delegate_to: localhost
    failed_when: (ssh_result.rc != 255 and ssh_result.rc != 0)
    when: found_ip == false

  - name: Add VM ip address to new groups vms
    add_host:
      name: "{{ ip_addr.stdout }}"
      groups: vms
    when: found_ip == false

  - debug:
      msg: "{{ groups['vms'] }} is the VM IP Address"
