---
- name: Prepare to run devstack
  hosts: localhost
  tasks:

  - name: grab a routed IP address for the vm
    become: yes
    shell: |
        virsh domifaddr "{{ name }}" |
        tail -n +3 | awk '{print $4}' |
        cut -d'/' -f1 |
        while read ipa ; do
            ping -c1 $ipa >& /dev/null;
            [[ $? -eq 0 ]] && echo "$ipa" && break;
        done
    register: ip_addr
    delegate_to: localhost
    until: ip_addr.rc == 0
    delay: 10
    retries: 12

  - name: ensure we found an IP address for this vm
    fail: msg="Could not find IP Address for '{{ name }}'"
    when: ip_addr.stdout is not defined or ip_addr.stdout == ""

  - name: avoid the ssh host authentication query
    shell: |
      ssh -O exit "{{ ip_addr.stdout }}"
      ssh-keygen -R "{{ ip_addr.stdout }}"
      ssh -o StrictHostKeyChecking=no -v root@"{{ ip_addr.stdout }}" true
    register: ssh_result
    delegate_to: localhost
    failed_when: (ssh_result.rc != 255 and ssh_result.rc != 0)
    when: true  # avoid linting warning

  - name: Add VM ip address to new groups vms
    add_host:
      name: "{{ ip_addr.stdout }}"
      groups: vms

- name: Get Devstack ready for running
  remote_user: root
  hosts: vms
  tasks:

  - name: verify root can ssh into the new vm.  If not, you'll need to add that via an ssh-copy-id or similar outside these plays
    become: yes
    shell: date

  - name: clone devstack
    git:
      repo: https://opendev.org/openstack/devstack.git
      dest: /root/devstack

  - name: build devstack prerequisites - create-stack-user.sh
    become: yes
    shell: /root/devstack/tools/create-stack-user.sh
    register: createstackuser

  - name: ensure /opt/stack has the correct perms
    become: yes
    file:
      path: "/opt/stack"
      state: directory
      owner: stack
      group: stack
      mode: "u=rwx,g=rx,o=rx"

  - name: ensure stack has a .ssh directory
    become: yes
    file:
      path: "/opt/stack/.ssh"
      state: directory
      owner: stack
      group: stack
      mode: "u=rwx,og="

  - name: allow authorised stack logins
    become: yes
    copy:
        src: /root/.ssh/authorized_keys
        dest: /opt/stack/.ssh/authorized_keys
        remote_src: yes
        owner: stack
        group: stack
        mode: u=rw,og=

- name: Startup Devstack, patching for things that we want
  remote_user: stack
  hosts: vms
  tasks:

  - name: clone devstack
    git:
      repo: https://opendev.org/openstack/devstack.git
      dest: /opt/stack/devstack

  - name: Template copy an ironicised devstack's local.conf
    template:
        src: devstack/local.conf.ironic.j2
        dest: /opt/stack/devstack/local.conf

  - name: clone extra openstack repositories
    git:
      repo: "https://opendev.org/openstack/{{ item }}.git"
      dest: "/opt/stack/{{ item }}"
    with_items:
      - "{{ extra_openstack_pkgs }}"
    ignore_errors: yes

  - name: Set up the user's name in git
    git_config:
      name: user.name
      value: "{{ git_user }}"
      scope: global

  - name: Set up the user's email in git
    git_config:
      name: user.email
      value: "{{ git_email }}"
      scope: global

  - name: cherry pick in patches from git repos
    shell: "cd /opt/stack/{{ item.repo }} && git fetch {{ item.cherry_pick }} && git cherry-pick FETCH_HEAD"
    with_items:
      - "{{ patches_to_apply }}"
    # We don't want to ignore errors here as if we are trying to cherry-pick in changes, we can't have local
    # conflicting changes

  - name: ensure introspection rules directory exists
    become: yes
    file:
      path: "/opt/stack/introspection"
      state: directory
      owner: stack
      group: stack
      mode: "u=rwx,g=rx,o=rx"

  - name: copy in introspection rules
    copy:
      src: files/introspection-rules.json
      dest: /opt/stack/introspection/rules.json

