---
- import_playbook: get-vm-ip-address.yml

- name: Support customised tinyipa images
  remote_user: root
  hosts: vms
  tasks:

  - name: check the source directory for tinyipa images exists
    stat:
      path: "{{ ipa_output_dir }}"
    register: ipa_dir
    delegate_to: localhost

  - fail:
      msg: Unable to find source directory for custom ipa images
    when: not ipa_dir.stat.exists and not ip_dir.stat.isdir

  - name: copy tinyipa image into vm
    copy:
      src: "{{ item }}"
      dest: /tmp
    with_items:
      - "{{ ipa_output_dir }}{{ ipa_agent_kernel[5:] }}"
      - "{{ ipa_output_dir}}{{ ipa_agent_ramdisk[5:] }}"
