---
- name: Prepare to run devstack
  hosts: localhost
  tasks:

  - pause:
      seconds: 30
      prompt: |
        *************************************************************************************
        *************************************************************************************
        **                                                                                 **
        **  WARNING: About to start devstack, this is NOT idempotent, '^C a' to exit now.  **
        **           Sleeping 30 seconds to give you time to stop this                     **
        **                                                                                 **
        *************************************************************************************
        *************************************************************************************
    when: start_devstack|bool

  - name: grab a routed IP address for the vm
    become: yes
    shell: |
        virsh domifaddr "{{ name }}" |
        tail -n +3 | awk '{print $4}' |
        cut -d'/' -f1 |
        while read ipa ; do
            ping -c1 $ipa >& /dev/null;
            [[ $? -eq 0 ]] && echo "$ipa" && break;
        done
    register: ip_addr
    delegate_to: localhost
    until: ip_addr.rc == 0
    delay: 10
    retries: 12

  - name: ensure we found an IP address for this vm
    fail: msg="Could not find IP Address for '{{ name }}'"
    when: ip_addr.stdout is not defined or ip_addr.stdout == ""

  - name: avoid the ssh host authentication query
    shell: |
      ssh -O exit "{{ ip_addr.stdout }}"
      ssh-keygen -R "{{ ip_addr.stdout }}"
      ssh -o StrictHostKeyChecking=no -v root@"{{ ip_addr.stdout }}" true
    register: ssh_result
    delegate_to: localhost
    failed_when: (ssh_result.rc != 255 and ssh_result.rc != 0)
    when: true  # avoid linting warning

  - name: Add VM ip address to new groups vms
    add_host:
      name: "{{ ip_addr.stdout }}"
      groups: vms

- name: Get Devstack ready for running
  remote_user: root
  hosts: vms
  tasks:

# NOTE(mrda): As of 20190812, an f29 host does not properly bring up baremetal nodes
#             Specifically, they drop into "clean failed" state.  Consequently the
#             following play will fail on f29

- name: Start devstack
  hosts: vms
  remote_user: stack
  tasks:

  - name: Check that devstack has what it needs to start successfully
    stat:
      path: "{{ item }}"
    with_items:
      - "{{ ipa_agent_kernel_url[7:] }}"
      - "{{ ipa_agent_ramdisk_url[7:] }}"
    register: file_deps

  - fail:
      msg: "{{ item }} not found"
    with_items: "{{ file_deps.results }}"
    when: not item.stat.exists

  - debug:
      msg: "{{ item.item }} is present in devstack"
    with_items: "{{ file_deps.results }}"
    when: item.stat.exists

  - name: start devstack
    shell: ./stack.sh
    args:
        chdir: /opt/stack/devstack
    register: stackoutput
    when: start_devstack|bool

  - name: ensure devstack started correctly
    fail: msg="devstack didn't succeed"
    when: start_devstack|bool and stackoutput.rc != 0

  - pause:
      seconds: 5
      prompt: |
        *********************************************************************
        *********************************************************************
        **                                                                 **
        **  You've requested not to start devstack.                        **
        **                                                                 **
        **  If you want to do that manually, you should do the following:  **
        **    ssh stack@$IPADDR                                            **
        **    cd /opt/stack/devstack                                       **
        **    ./stack.sh                                                   **
        **                                                                 **
        *********************************************************************
        *********************************************************************
    when: not start_devstack
