---
- name: Prepare to run devstack
  hosts: localhost
  tasks:

  - pause:
      seconds: 30
      prompt: |
        *************************************************************************************
        *************************************************************************************
        **                                                                                 **
        **  WARNING: About to start devstack, this is NOT idempotent, '^C a' to exit now.  **
        **           Sleeping 30 seconds to give you time to stop this                     **
        **                                                                                 **
        *************************************************************************************
        *************************************************************************************
    when: start_devstack|bool

- import_playbook: get-vm-ip-address.yml

- name: Get Devstack ready for running
  remote_user: root
  hosts: vms
  tasks:

# NOTE(mrda): As of 20190812, an f29 host does not properly bring up baremetal nodes
#             Specifically, they drop into "clean failed" state.  Consequently the
#             following play will fail on f29

- name: Start devstack
  hosts: vms
  remote_user: stack
  tasks:

  - name: Check that devstack has what it needs to start successfully
    stat:
      path: "{{ item }}"
    with_items:
      - "{{ ipa_agent_kernel }}"
      - "{{ ipa_agent_ramdisk }}"
    register: file_deps

  - fail:
      msg: "{{ item }} not found"
    with_items: "{{ file_deps.results }}"
    when: not item.stat.exists

  - debug:
      msg: "{{ item.item }} is present in devstack"
    with_items: "{{ file_deps.results }}"
    when: item.stat.exists

  - name: start devstack
    shell: ./stack.sh
    args:
        chdir: /opt/stack/devstack
    register: stackoutput
    when: start_devstack|bool

  - name: ensure devstack started correctly
    fail: msg="devstack didn't succeed"
    when: start_devstack|bool and stackoutput.rc != 0

  - pause:
      seconds: 5
      prompt: |
        *********************************************************************
        *********************************************************************
        **                                                                 **
        **  You've requested not to start devstack.                        **
        **                                                                 **
        **  If you want to do that manually, you should do the following:  **
        **    ssh stack@$IPADDR                                            **
        **    cd /opt/stack/devstack                                       **
        **    ./stack.sh                                                   **
        **                                                                 **
        *********************************************************************
        *********************************************************************
    when: not start_devstack
